package com.example.piceditor.templates_editor

import android.graphics.RectF

// AUTO-GENERATED by tools/gen_cells.ps1 from tools/cells_config.ps1. Do not edit by hand.
object TemplateCells {

    val rects: Map<String, List<RectF>> = mapOf(
        "bd01" to listOf(RectF(343f, 496f, 801f, 985f), RectF(129f, 986f, 588f, 1476f), RectF(523f, 1494f, 981f, 1983f)),
        "bd02" to listOf(RectF(0f, 1431f, 336f, 1796f), RectF(393f, 1431f, 732f, 1796f), RectF(789f, 1431f, 1125f, 1796f)),
        "bd03" to listOf(RectF(497f, 90f, 1054f, 834f), RectF(109f, 1075f, 653f, 1802f)),
        "bd04" to listOf(RectF(655f, 422f, 1082f, 986f), RectF(695f, 1179f, 1061f, 1668f)),
        "bd05" to listOf(RectF(267f, 642f, 955f, 1567f)),
        "bd06" to listOf(RectF(152f, 158f, 963f, 1230f)),
        "bd07" to listOf(RectF(118f, 566f, 966f, 1374f)),
        "bd08" to listOf(RectF(231f, 711f, 894f, 1457f)),
        "bd09" to listOf(RectF(66f, 557f, 585f, 1088f), RectF(599f, 1220f, 1034f, 1663f)),
        "bd10" to listOf(RectF(608f, 424f, 1083f, 889f), RectF(608f, 935f, 1083f, 1402f), RectF(608f, 1449f, 1083f, 1924f), RectF(88f, 1449f, 562f, 1924f)),
        "cp01" to listOf(RectF(222f, 295f, 990f, 775f), RectF(165f, 775f, 905f, 1295f)),
        "cp02" to listOf(RectF(0f, 0f, 1125f, 667f), RectF(0f, 667f, 1125f, 1333f), RectF(0f, 1333f, 1125f, 2000f)),
        "cp03" to listOf(RectF(84f, 92f, 730f, 576f), RectF(202f, 631f, 848f, 1111f), RectF(323f, 1166f, 959f, 1662f)),
        "cp04" to listOf(RectF(500f, 40f, 1069f, 788f), RectF(111f, 1085f, 672f, 1833f)),
        "cp05" to listOf(RectF(117f, 161f, 531f, 712f), RectF(416f, 826f, 855f, 1412f)),
        "cp06" to listOf(RectF(465f, 495f, 812f, 955f), RectF(193f, 1294f, 547f, 1649f)),
        "cp07" to listOf(RectF(167f, 357f, 723f, 842f), RectF(365f, 1285f, 918f, 1766f)),
        "cp08" to listOf(RectF(459f, 559f, 993f, 966f), RectF(296f, 1145f, 661f, 1561f)),
        "cp09" to listOf(RectF(145f, 344f, 560f, 759f), RectF(603f, 344f, 1017f, 759f), RectF(145f, 803f, 560f, 1217f), RectF(603f, 803f, 1017f, 1217f), RectF(145f, 1261f, 560f, 1676f), RectF(603f, 1261f, 1017f, 1676f)),
        "gs01" to listOf(RectF(224f, 836f, 944f, 1684f)),
        "gs02" to listOf(RectF(188f, 352f, 936f, 836f), RectF(188f, 872f, 936f, 1284f)),
        "gs03" to listOf(RectF(86f, 480f, 554f, 1096f), RectF(565f, 482f, 1029f, 1090f), RectF(579f, 1118f, 1035f, 1712f), RectF(86f, 1092f, 554f, 1702f)),
        "gs04" to listOf(RectF(32f, 52f, 368f, 708f), RectF(392f, 52f, 732f, 708f), RectF(756f, 52f, 1092f, 708f), RectF(32f, 1292f, 368f, 1944f), RectF(392f, 1292f, 732f, 1944f), RectF(756f, 1292f, 1092f, 1944f)),
        "gs05" to listOf(RectF(77f, 77f, 1049f, 1051f), RectF(58f, 1591f, 459f, 1970f)),
        "gs06" to listOf(RectF(68f, 620f, 1056f, 1140f), RectF(552f, 1172f, 1056f, 1628f)),
        "gs07" to listOf(RectF(61f, 186f, 526f, 662f), RectF(634f, 780f, 1072f, 1223f), RectF(44f, 1393f, 500f, 1854f)),
        "gs08" to listOf(RectF(68f, 478f, 515f, 1065f), RectF(665f, 949f, 1082f, 1378f)),
        "gs09" to listOf(RectF(519f, 477f, 997f, 814f), RectF(91f, 1006f, 600f, 1370f)),
        "gs10" to listOf(RectF(222f, 628f, 856f, 1306f)),
        "is01" to listOf(RectF(83f, 275f, 542f, 900f), RectF(52f, 973f, 510f, 1598f), RectF(615f, 399f, 1073f, 1024f), RectF(583f, 1097f, 1042f, 1722f)),
        "is02" to listOf(RectF(188f, 300f, 1004f, 1112f)),
        "is03" to listOf(RectF(251f, 599f, 901f, 1288f)),
        "is04" to listOf(RectF(113f, 158f, 523f, 573f), RectF(604f, 729f, 1034f, 1173f), RectF(95f, 1366f, 526f, 1806f)),
        "is05" to listOf(RectF(123f, 266f, 467f, 746f), RectF(503f, 410f, 1032f, 892f), RectF(162f, 775f, 508f, 1255f), RectF(542f, 925f, 1073f, 1407f), RectF(203f, 1284f, 545f, 1764f)),
        "is06" to listOf(RectF(53f, 329f, 530f, 1019f), RectF(573f, 314f, 1075f, 905f), RectF(40f, 1135f, 550f, 1595f), RectF(574f, 1054f, 1056f, 1751f)),
        "is07" to listOf(RectF(132f, 198f, 845f, 880f), RectF(287f, 879f, 1087f, 1669f)),
        "is08" to listOf(RectF(231f, 110f, 783f, 662f), RectF(49f, 1295f, 601f, 1847f), RectF(502f, 736f, 1054f, 1288f)),
        "is09" to listOf(RectF(136f, 552f, 386f, 851f), RectF(430f, 552f, 989f, 1536f), RectF(136f, 895f, 386f, 1194f), RectF(136f, 1238f, 386f, 1536f)),
        "is10" to listOf(RectF(571f, 181f, 1055f, 680f), RectF(105f, 1105f, 549f, 1560f)),
        "is11" to listOf(RectF(116f, 252f, 564f, 884f), RectF(468f, 1120f, 1004f, 1880f)),
        "is12" to listOf(RectF(73f, 309f, 434f, 777f), RectF(497f, 103f, 974f, 817f), RectF(145f, 1419f, 921f, 1867f)),
        "is13" to listOf(RectF(102f, 603f, 741f, 1361f), RectF(786f, 601f, 1052f, 947f), RectF(786f, 1015f, 1052f, 1360f), RectF(786f, 1427f, 1052f, 1773f), RectF(102f, 1426f, 368f, 1772f)),
        "is14" to listOf(RectF(562f, 0f, 1125f, 556f), RectF(564f, 556f, 1125f, 1120f), RectF(564f, 1440f, 1125f, 2000f), RectF(0f, 1119f, 564f, 1689f)),
        "is15" to listOf(RectF(176f, 567f, 949f, 1060f), RectF(176f, 1255f, 949f, 1749f)),
        "sm01" to listOf(RectF(70f, 174f, 1058f, 644f), RectF(71f, 761f, 1057f, 1259f), RectF(69f, 1377f, 1058f, 1847f)),
        "sm02" to listOf(RectF(149f, 520f, 588f, 957f), RectF(487f, 366f, 1024f, 704f), RectF(149f, 989f, 585f, 1425f), RectF(612f, 805f, 978f, 1261f), RectF(538f, 1285f, 1004f, 1650f)),
        "sm03" to listOf(RectF(149f, 367f, 733f, 751f), RectF(442f, 863f, 1025f, 1248f), RectF(404f, 1450f, 988f, 1834f)),
        "sm04" to listOf(RectF(454f, 253f, 949f, 1061f), RectF(166f, 964f, 659f, 1783f)),
        "sm05" to listOf(RectF(270f, 330f, 895f, 1035f), RectF(710f, 725f, 1018f, 1030f), RectF(625f, 1036f, 933f, 1340f), RectF(540f, 1360f, 848f, 1638f)),
        "sm06" to listOf(RectF(52f, 269f, 615f, 716f), RectF(635f, 269f, 1073f, 883f), RectF(52f, 737f, 489f, 1351f), RectF(510f, 904f, 1073f, 1351f), RectF(52f, 1372f, 1073f, 1820f)),
        "sm07" to listOf(RectF(0f, 0f, 562f, 667f), RectF(562f, 0f, 1125f, 667f), RectF(0f, 667f, 562f, 1334f), RectF(562f, 667f, 1125f, 1334f), RectF(0f, 1334f, 562f, 2000f), RectF(562f, 1334f, 1125f, 2000f)),
        "sm08" to listOf(RectF(21f, 151f, 368f, 620f), RectF(21f, 640f, 368f, 1109f), RectF(21f, 1130f, 368f, 1599f), RectF(388f, 286f, 735f, 755f), RectF(388f, 776f, 735f, 1245f), RectF(388f, 1265f, 735f, 1734f), RectF(757f, 400f, 1104f, 869f), RectF(757f, 889f, 1104f, 1358f), RectF(757f, 1379f, 1104f, 1848f)),
        "sm09" to listOf(RectF(133f, 188f, 527f, 583f), RectF(110f, 625f, 506f, 1020f), RectF(88f, 1062f, 483f, 1457f), RectF(608f, 763f, 1004f, 1159f), RectF(626f, 1200f, 1022f, 1596f)),
        "sp01" to listOf(RectF(175f, 329f, 946f, 924f), RectF(147f, 1098f, 951f, 1687f))
    )

    // Goc xoay (do) song song voi rects[id]. Chi liet ke template co o nghieng.
    val angles: Map<String, List<Float>> = mapOf(
        "cp03" to listOf(-12.7f, -12.5f, -12.9f),
        "cp06" to listOf(5f, -4.5f),
        "is05" to listOf(-4.5f, -4.5f, -4.5f, -4f, -4.5f),
        "sm01" to listOf(-7.5f, 0f, -7f),
        "sm02" to listOf(0f, 0f, 0f, 9.5f, 0f),
        "sm03" to listOf(9f, -10.5f, 14.5f),
        "sm04" to listOf(-8f, 4.5f),
        "sm05" to listOf(0f, 15.5f, 15.4f, 15.7f),
        "sm09" to listOf(3f, 3f, 3f, -2.5f, -2.5f),
        "sp01" to listOf(3.4f, -5.4f)
    )

    val masks: Map<String, MaskMode> = mapOf(
        "sm04" to MaskMode.GRAY2,
        "sm01" to MaskMode.WHITE,
        "sm02" to MaskMode.GRAY2,
        "is06" to MaskMode.WHITE,
        "is05" to MaskMode.GRAY,
        "sm03" to MaskMode.GRAY,
        "sp01" to MaskMode.GRAY,
        "cp06" to MaskMode.WHITE,
        "sm05" to MaskMode.GRAY,
        "is12" to MaskMode.GRAY,
        "sm07" to MaskMode.GRAY
    )
}

