# Generate TemplateCells.kt from cells_config.ps1. ASCII only (ids/numbers/MaskMode are ASCII).
. "D:\EZTech\EZTechApp\collage_pic_editor\tools\cells_config.ps1"

$dst="D:\EZTech\EZTechApp\collage_pic_editor\app\src\main\java\com\example\piceditor\templates_editor\TemplateCells.kt"
$sb=New-Object System.Text.StringBuilder
[void]$sb.AppendLine('package com.example.piceditor.templates_editor')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('import android.graphics.RectF')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// AUTO-GENERATED by tools/gen_cells.ps1 from tools/cells_config.ps1. Do not edit by hand.')
[void]$sb.AppendLine('object TemplateCells {')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    val rects: Map<String, List<RectF>> = mapOf(')
$keys=@($CELLS.Keys)
for($i=0;$i -lt $keys.Count;$i++){
  $id=$keys[$i]
  $rr=$CELLS[$id]
  if($rr.Count -ge 1 -and ($rr[0] -is [int] -or $rr[0] -is [double])){ $rr=@(,$rr) }  # single-cell flattened -> rewrap
  $parts=@()
  foreach($r in $rr){ $parts += ("RectF({0}f, {1}f, {2}f, {3}f)" -f $r[0],$r[1],$r[2],$r[3]) }
  $comma= if($i -lt $keys.Count-1){','}else{''}
  [void]$sb.AppendLine(('        "{0}" to listOf({1}){2}' -f $id, ($parts -join ', '), $comma))
}
[void]$sb.AppendLine('    )')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    val masks: Map<String, MaskMode> = mapOf(')
$mkeys=@($MASKS.Keys)
for($i=0;$i -lt $mkeys.Count;$i++){
  $id=$mkeys[$i]
  $comma= if($i -lt $mkeys.Count-1){','}else{''}
  [void]$sb.AppendLine(('        "{0}" to MaskMode.{1}{2}' -f $id, $MASKS[$id], $comma))
}
[void]$sb.AppendLine('    )')
[void]$sb.AppendLine('}')
$sb.ToString() | Out-File -FilePath $dst -Encoding ascii
Write-Host ("Wrote TemplateCells.kt: {0} cell-sets, {1} mask overrides" -f $keys.Count, $mkeys.Count)
