# Generate TemplateCells.kt from cells_config.ps1. ASCII only.
# Cell = @(x0,y0,x1,y1) (o thang) hoac @(x0,y0,x1,y1,angleDeg) (o xoay quanh tam).
. "D:\EZTech\EZTechApp\collage_pic_editor\tools\cells_config.ps1"

$inv=[System.Globalization.CultureInfo]::InvariantCulture
function FmtF($v){ return ([double]$v).ToString($inv) + 'f' }

$dst="D:\EZTech\EZTechApp\collage_pic_editor\app\src\main\java\com\example\piceditor\templates_editor\TemplateCells.kt"
$sb=New-Object System.Text.StringBuilder
[void]$sb.AppendLine('package com.example.piceditor.templates_editor')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('import android.graphics.RectF')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// AUTO-GENERATED by tools/gen_cells.ps1 from tools/cells_config.ps1. Do not edit by hand.')
[void]$sb.AppendLine('object TemplateCells {')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    val rects: Map<String, List<RectF>> = mapOf(')
$keys=@($CELLS.Keys)
$angleEntries=[ordered]@{}
for($i=0;$i -lt $keys.Count;$i++){
  $id=$keys[$i]
  $rr=$CELLS[$id]
  if($rr.Count -ge 1 -and ($rr[0] -is [int] -or $rr[0] -is [double])){ $rr=@(,$rr) }  # single-cell flattened -> rewrap
  $parts=@(); $angs=@(); $hasAngle=$false
  foreach($r in $rr){
    $parts += ("RectF({0}, {1}, {2}, {3})" -f (FmtF $r[0]),(FmtF $r[1]),(FmtF $r[2]),(FmtF $r[3]))
    if($r.Count -ge 5){ $angs += (FmtF $r[4]); if([double]$r[4] -ne 0){ $hasAngle=$true } }
    else { $angs += '0f' }
  }
  if($hasAngle){ $angleEntries[$id]=$angs }
  $comma= if($i -lt $keys.Count-1){','}else{''}
  [void]$sb.AppendLine(('        "{0}" to listOf({1}){2}' -f $id, ($parts -join ', '), $comma))
}
[void]$sb.AppendLine('    )')
[void]$sb.AppendLine('')
# angles map: chi gom template co o xoay (angle != 0). Thieu -> coi nhu tat ca 0.
[void]$sb.AppendLine('    // Goc xoay (do) song song voi rects[id]. Chi liet ke template co o nghieng.')
[void]$sb.AppendLine('    val angles: Map<String, List<Float>> = mapOf(')
$akeys=@($angleEntries.Keys)
for($i=0;$i -lt $akeys.Count;$i++){
  $id=$akeys[$i]
  $comma= if($i -lt $akeys.Count-1){','}else{''}
  [void]$sb.AppendLine(('        "{0}" to listOf({1}){2}' -f $id, ($angleEntries[$id] -join ', '), $comma))
}
[void]$sb.AppendLine('    )')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('    val masks: Map<String, MaskMode> = mapOf(')
$mkeys=@($MASKS.Keys)
for($i=0;$i -lt $mkeys.Count;$i++){
  $id=$mkeys[$i]
  $comma= if($i -lt $mkeys.Count-1){','}else{''}
  [void]$sb.AppendLine(('        "{0}" to MaskMode.{1}{2}' -f $id, $MASKS[$id], $comma))
}
[void]$sb.AppendLine('    )')
[void]$sb.AppendLine('}')
$sb.ToString() | Out-File -FilePath $dst -Encoding ascii
Write-Host ("Wrote TemplateCells.kt: {0} cell-sets, {1} with angles, {2} mask overrides" -f $keys.Count, $akeys.Count, $mkeys.Count)
